name: "dbt_pilot"
version: "1.0.0"
config-version: 2

profile: "dbt_pilot"

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_pilot:
    staging:
      +materialized: view
    marts:
      +materialized: table
